# Loading Libraries

In [1]:
#Importing all libraries needed

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set()
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import StandardScaler
import pickle

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_type_1  Reason_type_2  Reason_type_3  Reason_type_4  Months  \
0              0              0              0              0       7   
1              0              0              0              0       7   
2              0              0              0              0       7   
3              1              0              0              1       7   
4              0              0              0              0       7   

   Weekday  Transportation Expense  Distance to Work  Age  \
0        1                     289                36   33   
1        1                     118                13   50   
2        2                     179                51   38   
3        3                     279                 5   39   
4        3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

# Create the target

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
target = np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [6]:
target

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteeism'] = target

In [8]:
data_preprocessed.head()

Reason_type_1  Reason_type_2  Reason_type_3  Reason_type_4  Months  \
0              0              0              0              0       7   
1              0              0              0              0       7   
2              0              0              0              0       7   
3              1              0              0              1       7   
4              0              0              0              0       7   

   Weekday  Transportation Expense  Distance to Work  Age  \
0        1                     289                36   33   
1        1                     118                13   50   
2        2                     179                51   38   
3        3                     279                 5   39   
4        3                     289                36   33   

   Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0                  239.554               30          0         2     1   
1                  239.554               31          0         1     0   
2                  239.554               31          0         0     0   
3                  239.554               24          0         2     0   
4                  239.554               30          0         2     1   

   Absenteeism Time in Hours  Excessive Absenteeism  
0                          4                      1  
1                          0                      0  
2                          2                      0  
3                          4                      1  
4                          2                      0

In [9]:
target.sum()/ target.shape[0]

0.45571428571428574

In [10]:
data_with_target =data_preprocessed.drop(['Absenteeism Time in Hours', 'Distance to Work',
       'Weekday', 'Daily Work Load Average'], axis=1)

In [11]:
data_with_target is data_preprocessed

False

# Selecting inputs for the regression

In [12]:
unscaled_inputs = data_with_target.iloc[:,:-1]

In [13]:
unscaled_inputs.head()

Reason_type_1  Reason_type_2  Reason_type_3  Reason_type_4  Months  \
0              0              0              0              0       7   
1              0              0              0              0       7   
2              0              0              0              0       7   
3              1              0              0              1       7   
4              0              0              0              0       7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                     289   33               30          0         2     1  
1                     118   50               31          0         1     0  
2                     179   38               31          0         0     0  
3                     279   39               24          0         2     0  
4                     289   33               30          0         2     1

# Standardization

In [14]:
unscaled_inputs.columns.values

array(['Reason_type_1', 'Reason_type_2', 'Reason_type_3', 'Reason_type_4',
       'Months', 'Transportation Expense', 'Age', 'Body Mass Index',
       'Education', 'Children', 'Pets'], dtype=object)

In [15]:
cols_to_scale = ['Months', 'Transportation Expense',
       'Age', 'Body Mass Index',
       'Children', 'Pets']
cols_noscale = ['Reason_type_1', 'Reason_type_2', 'Reason_type_3', 'Reason_type_4','Education']

In [16]:
columns_to_scale = unscaled_inputs[cols_to_scale]
noscale_columns = unscaled_inputs[cols_noscale]

In [17]:
columns_to_scale.head()

Months  Transportation Expense  Age  Body Mass Index  Children  Pets
0       7                     289   33               30         2     1
1       7                     118   50               31         1     0
2       7                     179   38               31         0     0
3       7                     279   39               24         2     0
4       7                     289   33               30         2     1

In [18]:
from sklearn.preprocessing import StandardScaler
absenteeism_scalar = StandardScaler()
absenteeism_scalar.fit(columns_to_scale)
scaled_inputs = absenteeism_scalar.transform(columns_to_scale)

In [22]:
scaled_inputs

array([[ 0.18272635,  1.00584437, -0.53606239,  0.76743118,  0.88046927,
         0.26848661],
       [ 0.18272635, -1.57468098,  2.13080317,  1.00263338, -0.01928035,
        -0.58968976],
       [ 0.18272635, -0.6541427 ,  0.24830984,  1.00263338, -0.91902997,
        -0.58968976],
       ...,
       [-0.3882935 ,  1.62456682, -1.32043461, -0.40857982, -0.91902997,
        -0.58968976],
       [-0.3882935 ,  0.19094163, -0.69293683, -0.40857982, -0.91902997,
        -0.58968976],
       [-0.3882935 ,  1.03602595,  0.56205873, -0.40857982, -0.01928035,
         0.26848661]])

In [23]:
type(scaled_inputs)

numpy.ndarray

In [24]:
noscale_columns = pd.DataFrame(noscale_columns, columns=cols_noscale)
scaled_inputs = pd.DataFrame(scaled_inputs, columns = cols_to_scale)

In [25]:
scaled_inputs.head()

Months  Transportation Expense       Age  Body Mass Index  Children  \
0  0.182726                1.005844 -0.536062         0.767431  0.880469   
1  0.182726               -1.574681  2.130803         1.002633 -0.019280   
2  0.182726               -0.654143  0.248310         1.002633 -0.919030   
3  0.182726                0.854936  0.405184        -0.643782  0.880469   
4  0.182726                1.005844 -0.536062         0.767431  0.880469   

       Pets  
0  0.268487  
1 -0.589690  
2 -0.589690  
3 -0.589690  
4  0.268487

In [26]:
total_inputs = pd.concat([noscale_columns, scaled_inputs], axis=1)

In [27]:
total_inputs.columns.values

array(['Reason_type_1', 'Reason_type_2', 'Reason_type_3', 'Reason_type_4',
       'Education', 'Months', 'Transportation Expense', 'Age',
       'Body Mass Index', 'Children', 'Pets'], dtype=object)

In [28]:
new_cols = ['Reason_type_1', 'Reason_type_2', 'Reason_type_3', 'Reason_type_4',
            'Months', 'Transportation Expense', 'Age','Body Mass Index', 'Education', 'Children', 'Pets']

In [29]:
total_inputs = total_inputs[new_cols]
total_inputs.head()

Reason_type_1  Reason_type_2  Reason_type_3  Reason_type_4    Months  \
0              0              0              0              0  0.182726   
1              0              0              0              0  0.182726   
2              0              0              0              0  0.182726   
3              1              0              0              1  0.182726   
4              0              0              0              0  0.182726   

   Transportation Expense       Age  Body Mass Index  Education  Children  \
0                1.005844 -0.536062         0.767431          0  0.880469   
1               -1.574681  2.130803         1.002633          0 -0.019280   
2               -0.654143  0.248310         1.002633          0 -0.919030   
3                0.854936  0.405184        -0.643782          0  0.880469   
4                1.005844 -0.536062         0.767431          0  0.880469   

       Pets  
0  0.268487  
1 -0.589690  
2 -0.589690  
3 -0.589690  
4  0.268487

# Train Test Split and Shuffling

# split

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(total_inputs, target, train_size=0.8, random_state=20)

In [32]:
print(X_train.shape, y_train.shape)

(560, 11) (560,)


In [33]:
print(X_test.shape, y_test.shape)

(140, 11) (140,)


# Modelling

In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [35]:
reg = LogisticRegression()

In [36]:
reg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [37]:
reg.score(X_train, y_train)

0.7857142857142857

In [38]:
model_outputs = reg.predict(X_train)

In [39]:
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [40]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [41]:
model_outputs==y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True, False,

In [42]:
np.sum(model_outputs==y_train)

440

In [43]:
model_outputs.shape[0]

560

In [44]:
np.sum(model_outputs==y_train)/model_outputs.shape[0]

0.7857142857142857

# Decision Tree Classifier

In [45]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()

In [46]:
clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [47]:
clf.score(X_train, y_train)

0.9142857142857143

In [48]:
dtc = clf.predict(X_train)

In [49]:
dtc==y_train

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [50]:
np.sum(dtc==y_train)/dtc.shape[0]

0.9142857142857143

# Back to Result of Logistic Regression

In [51]:
reg.intercept_

array([-1.06837273])

In [52]:
reg.coef_

array([[ 1.14740977,  0.69729029,  2.96006712,  1.14740977,  0.20638455,
         0.53180077, -0.17582985,  0.2549443 , -0.42455479,  0.29964059,
        -0.42843052]])

In [53]:
total_inputs.columns.values

array(['Reason_type_1', 'Reason_type_2', 'Reason_type_3', 'Reason_type_4',
       'Months', 'Transportation Expense', 'Age', 'Body Mass Index',
       'Education', 'Children', 'Pets'], dtype=object)

In [54]:
feature_name = total_inputs.columns.values

In [55]:
summary_table = pd.DataFrame(columns = ['feature_name'], data=feature_name)
summary_table['coefficients'] = np.transpose(reg.coef_)

In [56]:
summary_table

feature_name  coefficients
0            Reason_type_1      1.147410
1            Reason_type_2      0.697290
2            Reason_type_3      2.960067
3            Reason_type_4      1.147410
4                   Months      0.206385
5   Transportation Expense      0.531801
6                      Age     -0.175830
7          Body Mass Index      0.254944
8                Education     -0.424555
9                 Children      0.299641
10                    Pets     -0.428431

In [57]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['intercepts', reg.intercept_[0]]
summary_table = summary_table.sort_index()

In [58]:
summary_table

feature_name  coefficients
0               intercepts     -1.068373
1            Reason_type_1      1.147410
2            Reason_type_2      0.697290
3            Reason_type_3      2.960067
4            Reason_type_4      1.147410
5                   Months      0.206385
6   Transportation Expense      0.531801
7                      Age     -0.175830
8          Body Mass Index      0.254944
9                Education     -0.424555
10                Children      0.299641
11                    Pets     -0.428431

In [59]:
summary_table['Odds_ratio'] = np.exp(summary_table.coefficients)

In [60]:
summary_table.sort_values('Odds_ratio', ascending = False)

feature_name  coefficients  Odds_ratio
3            Reason_type_3      2.960067   19.299267
1            Reason_type_1      1.147410    3.150023
4            Reason_type_4      1.147410    3.150023
2            Reason_type_2      0.697290    2.008303
6   Transportation Expense      0.531801    1.701994
10                Children      0.299641    1.349374
8          Body Mass Index      0.254944    1.290390
5                   Months      0.206385    1.229226
7                      Age     -0.175830    0.838761
9                Education     -0.424555    0.654061
11                    Pets     -0.428431    0.651531
0               intercepts     -1.068373    0.343567

# Backward Elimination

Eliminate 

# Model testing

In [61]:
reg.score(X_test, y_test)

0.7571428571428571

In [62]:
predicted_proba = reg.predict_proba(X_test)
predicted_proba

array([[0.72184206, 0.27815794],
       [0.66499823, 0.33500177],
       [0.48819497, 0.51180503],
       [0.80612356, 0.19387644],
       [0.08245745, 0.91754255],
       [0.29529518, 0.70470482],
       [0.31696467, 0.68303533],
       [0.10612295, 0.89387705],
       [0.8561101 , 0.1438899 ],
       [0.76661882, 0.23338118],
       [0.10118672, 0.89881328],
       [0.0227342 , 0.9772658 ],
       [0.05225799, 0.94774201],
       [0.20270037, 0.79729963],
       [0.24483736, 0.75516264],
       [0.6598835 , 0.3401165 ],
       [0.74470787, 0.25529213],
       [0.12472701, 0.87527299],
       [0.41502224, 0.58497776],
       [0.03925449, 0.96074551],
       [0.76747394, 0.23252606],
       [0.80612356, 0.19387644],
       [0.33195589, 0.66804411],
       [0.33195589, 0.66804411],
       [0.20530022, 0.79469978],
       [0.81588704, 0.18411296],
       [0.57319814, 0.42680186],
       [0.88026242, 0.11973758],
       [0.11852739, 0.88147261],
       [0.80612356, 0.19387644],
       [0.

In [63]:
predicted_proba.shape

(140, 2)

In [64]:
predicted_proba[:,1]

array([0.27815794, 0.33500177, 0.51180503, 0.19387644, 0.91754255,
       0.70470482, 0.68303533, 0.89387705, 0.1438899 , 0.23338118,
       0.89881328, 0.9772658 , 0.94774201, 0.79729963, 0.75516264,
       0.3401165 , 0.25529213, 0.87527299, 0.58497776, 0.96074551,
       0.23252606, 0.19387644, 0.66804411, 0.66804411, 0.79469978,
       0.18411296, 0.42680186, 0.11973758, 0.88147261, 0.19387644,
       0.88480278, 0.65233494, 0.72862414, 0.90903902, 0.19387644,
       0.93139994, 0.15130197, 0.81970491, 0.303836  , 0.52861793,
       0.18483292, 0.45723059, 0.16706452, 0.52861793, 0.80629666,
       0.70955031, 0.72451147, 0.27815794, 0.19003565, 0.17611908,
       0.61696276, 0.43774935, 0.70470482, 0.25044703, 0.83329625,
       0.36174487, 0.86182827, 0.19992026, 0.48235214, 0.49707605,
       0.69386122, 0.69229672, 0.27402048, 0.83863615, 0.13923151,
       0.25512421, 0.18534876, 0.15130197, 0.81910397, 0.83274405,
       0.15130197, 0.40597677, 0.91690149, 0.36947424, 0.50046

# Saving the model using Pickle

In [65]:
import pickle

In [66]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

 We must scale the Absenteeism Scaler too

In [67]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scalar, file)